<a href="https://colab.research.google.com/github/rahman-maiyat/Simulation.modeling.lab/blob/main_bug_fix/Copy_of_022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


In [ ]:
# Sample scalar and array inputs
scalar = 3.7
arr = np.array([1, 2, 4, 6, 5,7])
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))  # Normalized and Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(arr / np.max(arr), -1, 1))
atan_values = np.arctan(arr)

print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)
print("asin:", asin_values)
print("acos:", acos_values)
print("atan:", atan_values)





sin: [ 0.84147098  0.90929743 -0.7568025  -0.2794155  -0.95892427  0.6569866 ]
cos: [ 0.54030231 -0.41614684 -0.65364362  0.96017029  0.28366219  0.75390225]
tan: [ 1.55740772 -2.18503986  1.15782128 -0.29100619 -3.38051501  0.87144798]
asin: [0.14334757 0.2897517  0.60824558 1.0296968  0.79560295 1.57079633]
acos: [1.42744876 1.28104463 0.96255075 0.54109953 0.77519337 0.        ]
atan: [0.78539816 1.10714872 1.32581766 1.40564765 1.37340077 1.42889927]


In [ ]:
matrix = np.array([[1.6, 2.7], [3.7, 4.7],[7.6,8.0]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)


Matrix:
 [[1.6 2.7]
 [3.7 4.7]
 [7.6 8. ]]

sin:
 [[ 0.9995736   0.42737988]
 [-0.52983614 -0.99992326]
 [ 0.96791967  0.98935825]]

cos:
 [[-0.02919952 -0.90407214]
 [-0.84810003 -0.01238866]
 [ 0.25125984 -0.14550003]]

tan:
 [[-34.23253274  -0.47272763]
 [  0.62473308  80.71276297]
 [  3.85226569  -6.79971146]]

asine:
 [[0.20135792 0.3442598 ]
 [0.48081283 0.62796598]
 [1.2532359  1.57079633]]

acosine:
 [[1.36943841 1.22653653]
 [1.0899835  0.94283034]
 [0.31756043 0.        ]]

atangent:
 [[1.01219701 1.21609067]
 [1.3068326  1.36115648]
 [1.43996893 1.44644133]]

exp:
 [[   4.95303242   14.87973172]
 [  40.44730436  109.94717245]
 [1998.1958951  2980.95798704]]

log (natural):
 [[0.47000363 0.99325177]
 [1.30833282 1.54756251]
 [2.02814825 2.07944154]]

abs:
 [[1.6 2.7]
 [3.7 4.7]
 [7.6 8. ]]

sqrt:
 [[1.26491106 1.64316767]
 [1.92353841 2.16794834]
 [2.75680975 2.82842712]]

rem (remainder when divided by 2):
 [[1.6 0.7]
 [1.7 0.7]
 [1.6 0. ]]

round:
 [[2. 3.]
 [4. 5.]
 [8. 8.

In [ ]:
matrix= np.array([[3.6, 1.7,7.8] ,[4.7, 1.8,7.7]])

# 1. Maximum value and index of max element
max_value = np.max(matrix)
max_index = np.argmax(matrix)  # Index of max element

# 2. Minimum value and index of min element
min_value = np.min(matrix)
min_index = np.argmin(matrix)  # Index of min element

matrix_length = len(matrix)  # Equivalent to MATLAB's length()

# 4. Sorting in ascending order
sorted_matrix = np.sort(matrix)



# 5. Sum of elements
sum_values = np.sum(matrix)

# 6. Product of elements
prod_values = np.prod(matrix)

# 7. Median value
median_value = np.median(matrix)

# 8. Mean value
mean_value = np.mean(matrix)

# 9. Standard deviation
std_dev = np.std(matrix)

# Display results
print("Max value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Length of vector:", matrix_length)
print("Sorted vector:", sorted_matrix)
print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)


Max value: 7.8 at index 2
Min value: 1.7 at index 1
Length of vector: 2
Sorted vector: [[1.7 3.6 7.8]
 [1.8 4.7 7.7]]
Sum of elements: 27.3
Product of elements: 3109.618512
Median value: 4.15
Mean value: 4.55
Standard deviation: 2.4864633518312713
